name: GitLab Mirror

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: Reflect
    steps:
      - uses: actions/checkout@v1
      - name: Kagami
        uses: javierparadadev/kagami@v1.0.0
        env:
          MIRROR_GIT_USERNAME: javierparadadev
          MIRROR_GIT_EMAIL: javierparada@pm.me
          MIRROR_GIT_HOSTNAME: gitlab.com
          MIRROR_GIT_PROJECT: deepfinder-py
          MIRROR_GIT_TOKEN: ${{ secrets.MIRROR_GIT_TOKEN }}